### ISSUE TITLE
Does this support nested data?

### ISSUE THREAD

**Issue by aneesdev** [WendellAdriel/laravel-validated-dto#1]
Hi,

nice package by the way. does this support nested data like in laravel requests? e.g `items.*` and `items.*.name` etc?

**Comment by aneesdev** [comment]
@WendellAdriel

**Comment by WendellAdriel** [comment]
@aneesdev yes, it supports the same validations that would apply to a request so you can validate nested data the same way and it will be available in the DTO like the other properties. If you find any issues with this please add here an example and I’ll be happy to take a look!
