### ISSUE TITLE
Casts

### ISSUE THREAD

**Issue by i-prikot** [WendellAdriel/laravel-validated-dto#10]
Hello. Thanks for the package. Why casts are only for validation? Can I use without validation?

**Comment by WendellAdriel** [comment]
This package main purpose is provide DTOs with data validation. So only properties that are listed in the rules that can be used. Even if you provide only `required` or `sometimes` rules to the properties. So you need to add some validation for the DTOs to properly work.

**Comment by i-prikot** [comment]
> This package main purpose is provide DTOs with data validation. So only properties that are listed in the rules that can be used. Even if you provide only `required` or `sometimes` rules to the properties. So you need to add some validation for the DTOs to properly work.

Ок, thanks.
