### ISSUE TITLE
Do not cast null properties

### ISSUE THREAD

**Issue by nickhhg** [WendellAdriel/laravel-validated-dto#13]
If you define a property as being nullable/optional, but that same property also has a defined cast to a DTO, a `CastException` is thrown when casting that property if the value is null, even after validation.

It seems reasonable to not want to cast null properties, and one could assume validation rules should be used to avoid nulls if they're unacceptable.

Example
```php
class MyCustomDto extends ValidatedDTO
{
    public string $required_property;

    // Note the use of nullable (?)
    public ?AnotherCustomDto $optional_property;

    protected function rules(): array
    {
        return [
            'required_property' => ['required'],
            'optional_property' => ['nullable'],
        ];
    }

    protected function casts(): array
    {
        return [
            'required_property' => new StringCast,
            'optional_property' => new DTOCast(AnotherCustomDto::class),
        ];
    }
}

$dto = new MyCustomDto([
    'required_property' => 'abc',
    'optional_property' => null,
]);
``` 

This kind of affects all casting, because all properties returned in `casts()` will attempt to be casted, but it's not much of an issue when casting to primitive types.

I looked into extending `ValidatedDTO` to include an exception for null properties, but methods where the casting occurs such as `ValidatedDTO::validatedData()`, are `private`, and would require duplicating code to work around.

Another approach is to extend the current set of castables to account for nulls, but the properties on the Carbon/DTO castables are `private` and not accessible. Leaving us to essentially duplicate them to add some additions.

**Comment by WendellAdriel** [comment]
Thanks for the feedback, @nickhhg!
I was already trying some approaches to deal with nullable properties.
I'll probably launch soon a new version with this support!

**Comment by WendellAdriel** [comment]
@nickhhg this is now supported on v2.4.0!

**Comment by nickhhg** [comment]
works great. thanks 👍
