### ISSUE TITLE
Dependencies in the composer.json file

### ISSUE THREAD

**Issue by ilzrv** [WendellAdriel/laravel-validated-dto#19]
Are you sure about the dependencies in the composer.json file? It seems half of them should be in require, not in require-dev.

**Comment by WendellAdriel** [comment]
Yes, I’m sure.
This is to be used with Laravel so these dependencies don’t need to be in the require.

**Comment by ilzrv** [comment]
But I can install your library not in a Laravel project. This is unacceptable.

**Comment by ilzrv** [comment]
Your package depends only on PHP ^8.0

**Comment by WendellAdriel** [comment]
You can install it, but it won't work because if you read the docs it says that it's a package for Laravel projects. I was thinking of creating a generic PHP version tho, but I didn't work on it yet.

**Comment by ilzrv** [comment]
It is incorrect to install the library if is not suitable for your project. For example, there may be different versions of Laravel, but your package will install in any version. 

If you think this is correct, there are no questions. But for example, open any popular package, for example from [Spatie](https://github.com/spatie/laravel-backup/blob/981cec4792cc3a38098c6a6323d0d6f6d837c9f5/composer.json#L21-L35)

**Comment by WendellAdriel** [comment]
@ilzrv I understood now the issue you said, my bad.
I'm going to create a PR in a few minutes and if you could help me review that it would be great!
Thanks for the help and sorry for not understanding at first.

**Comment by ilzrv** [comment]
That is fine! Thanks!

**Comment by WendellAdriel** [comment]
@ilzrv the PR was created, can you take a look at it, please?

**Comment by ilzrv** [comment]
@WendellAdriel  Yep, done
