### ISSUE TITLE
Possibility to expose the "real property" failing the validation for nested DTOs?

### ISSUE THREAD

**Issue by arunbabucode** [WendellAdriel/laravel-validated-dto#34]
First of all, great package, thanks for that.

I was looking at the possibility of bringing and throwing errors on "real property" which is failing the validation. By real property, I mean, in the case of a deeply nested DTO.

For example, my DTOs are deeply nested and utilized something like suggested in this comment https://github.com/WendellAdriel/laravel-validated-dto/issues/24#issuecomment-1523089374.

Now I have a couple of collections of properties in the top-level DTO, let's call `ADTO.php`, which has properties, `b` and `c`. The `b` property is a collection of DTO implementing another DTO, say, `BDTO.php`. Then inside `BDTO.php`, I have a property called `d`, which is again a collection of DTO, say `DDTO.php` which has properties `e` and `f`.

Now if something is failing on the validation of `DDTO.php`, say property `e` failed validation, since it's a nested DTO called by `ADTO.php`, it says, the property `b` failed (which is of course correct). However, it is painful now to identify which property inside it failed since it's a deeply nested structure. 

I was wondering if it's possible to say property `b` failed of `ADTO.php` additionally with `e` property of `DDTO.php`, so I can get a clear understanding of which nested property exactly failed.

Please let me know if the explanation is not clear.

**Comment by WendellAdriel** [comment]
Hmmm, that's an interesting case.
Is it possible for you to provide a demo repository with this issue so I can take a further look at it, please?

**Comment by WendellAdriel** [comment]
@arunbabucode is it possible for you to provide a minimal demo repository with this issue so we can take a further look at this, please?

**Comment by i-prikot** [comment]
Hi. I think this is the problem here.
```
class CompanyOwnerDTO extends ValidatedDTO
{
    public UserDTO $user;
    public CompanyDTO $company;
    ...

    protected function rules(): array
    {
        return [
            'user' => ['required','array'],
            'company' => ['required','array'],
        ];
    }

    protected function casts(): array
    {
        return [
            'user' => new DTOCast(UserDTO::class),
            'company' => new DTOCast(CompanyDTO::class)
        ];
    }
}
```
```
class CompanyDTO extends ValidatedDTO
{
    /**
     * Defines the validation rules for the DTO.
     */
    protected function rules(): array
    {
        return [
            'name' => ['required', 'string'],
        ];
    }
}
```
```
class UserDTO extends ValidatedDTO
{
    public $name;

    public $email;

    public $password;
    
    /**
     * Defines the validation rules for the DTO.
     */
    protected function rules(): array
    {
        return [
            'name' => ['required', 'string'],
            'email' => ['required','email'],
            'password' => ['required','confirmed'],
        ];
    }
}
```

CompanyOwnerDTO will return array `[name =>[validation.required]]` UserDTO, CompanyDTO has field «name». Which class does the error belong to? Answer expected: `[company.name =>[validation.required]]` or `[user.name =>[validation.required]]`

**Comment by WendellAdriel** [comment]
@i-prikot are you able to put a minimal example of the issue in a repo and send it here so I can take a look at it, please?
