### ISSUE TITLE
Mapping deeply nested values

### ISSUE THREAD

**Issue by bnzo** [WendellAdriel/laravel-validated-dto#40]
There are some cases where mapping has to be deeper than one level:

```php
    protected function mapBeforeValidation(): array
    {
        return [
            'work_street' => 'user.addresses.work.street',
        ];
    }
```

```php
    protected function mapBeforeExport(): array
    {
        return [
            'user.addresses.work.street' => 'work_street',
        ];
    }
```

Thinking loud, even mapping like `user.addresses.3.street` might be interesting?

**Comment by WendellAdriel** [comment]
That's a good idea, but I think this could be already achievable with nested DTOs where you define the map functions. I didn't test tho because I didn't have the need yet, but if you want to try to see if it's possible, I'm curious about it.

**Comment by bnzo** [comment]
Yes it is already working well by creating multiple nested DTOs. The goal here is to avoid multiple DTOs creation just for one or two fields, and I also like the dot syntax easier to read.
I will investigate the `mapData` function and see what I can do.

**Comment by WendellAdriel** [comment]
I get it, but the idea of DTOs is to map all the data you have, it doesn't make much sense to have an object or an array of objects that are not mapped to another DTO. In the example that you sent you should have at least 3 DTOs:

1. UserDTO to map the user data
2. AddressesDTO to map the type of addresses that you support
3. AddressDTO to map each individual address data or even WorkAddressDTO, and PersonalAddressDTO if they have different structures.

**Comment by bnzo** [comment]
Agreed, it should map all the data. Having 3 DTOs in this case makes perfectly sense.

Now I do not have a concrete example but sometimes you can face this kind of situation: 
Considering this model case

```php
class User extends Model
{
    protected $fillable = [
        'first_name',
        'email', //work email
        'street' //work street
        'city', //work city
    ];
}
```
You should be able to map it like so:

```php
    protected function mapBeforeExport(): array
    {
        return [
            'user.first_name' => 'first_name',
            'user.emails.work => 'email',
            'user.addresses.work.street' => 'street',
            'user.addresses.work.street' => 'city',
        ];
    }
```

I didn't try it that way but, maybe there is another better solution?

**Comment by WendellAdriel** [comment]
If you need to map your DTO that has the structure in the mapBeforeExport to that User model, you'll need at least the three DTOs I sent above because this is needed to map the data structure for each object/list.

**Comment by bnzo** [comment]
I ended by keeping the existing structure and reflect it with nested DTOs. I do extra "shortcut mapping" on an intermediate layer, which adds complexity but it works. It could be better to have like so for future implementations anyway. Thanks!
