### ISSUE TITLE
Minor issue with the casts method being generated as `abstract`

### ISSUE THREAD

**Issue by IDTitanium** [WendellAdriel/laravel-validated-dto#7]
The stub file has the abstract keyword on the casts method, which is clearly not the intention of the casts method. 

So, currently, when you run the command to generate a validated DTO, you get `abstract protected function casts(): array.`

**Comment by IDTitanium** [comment]
I have created a PR here https://github.com/WendellAdriel/laravel-validated-dto/pull/6 to fix the issue.

**Comment by WendellAdriel** [comment]
Nice catch, thanks for the help!
Merged 😎
