### ISSUE TITLE
Declaration of WendellAdriel\ValidatedDTO\SimpleDTO::toJson(): string must be compatible with Illuminate\Contracts\Support\Jsonable::toJson($options = 0)

### ISSUE THREAD

**Issue by patriziotomato** [WendellAdriel/laravel-validated-dto#85]
Using a DTO in context of Laravel may lead to this exception, so I'm without a lot of arguing I'd recommand to make that compatible. I'm opening a pull request for this.

**Comment by WendellAdriel** [comment]
That's a good catch! 🔥 
I just released v3.8.1 with this fix!
Thanks a lot for the contribution! 💪
