### ISSUE TITLE
Add possibility to get data without nulls in map transformation

### ISSUE THREAD

**Issue by MuminovicAnel** [WendellAdriel/laravel-validated-dto#87]
Hello!

Your package is really great and convenient for the use case of our team. :)

I wanted to know if there as a possiblity to add the option to get data without null properties from the DTO ?

Because I need to overwrite the toJson or toArray methods like this in every DTO.

```php
public function toJson($options = 0): string
{
        $dataWithoutNulls = array_filter($this->buildDataForExport(), fn($value) => !is_null($value));
        return json_encode($dataWithoutNulls, $options);
}
```

Thanks!

**Comment by WendellAdriel** [comment]
Hey @MuminovicAnel.
I think this is a use case that should be handled in the userland, not in the library itself.

IMO the best way of dealing with this would be to create a `BaseDTO` class that extends from the `SimpleDTO` or `ValidatedDTO` one and on it you can add two new methods: `toNonNullableJson` and `toNonNullableArray` then in your DTOs, extend from your own `BaseDTO` class instead.

A second approach is to create a Trait and add these two methods in the Trait and in the DTOs you need that you can add the trait to it.

**Comment by MuminovicAnel** [comment]
Hey @WendellAdriel 

Thanks for the suggestion, I will go with the trait, that was a good idea. It doesn't add too much code and it lets the user use it or not.

Have a nice day!
