### ISSUE TITLE
Add convert strategy

### ISSUE THREAD

**Issue by meysam1717** [WendellAdriel/laravel-validated-dto#90]
Generated DTO class could accept from and to convert strategies. They could support nested strategies.
I provide some examples below that they even show hierarchy.

```php
[#ConvertStrategy(from: ConvertStrategy::SnakeCase, to: ConvertStrategy::PascalCase)]
Class UserDTO {}
```
```php
[#ConvertStrategy(fromArray: ConvertStrategy::SnakeCase, toModel: ConvertStrategy::PascalCase)]
Class UserDTO {}
```
```php
Class UserDTO {

    [#ConvertStrategy(from: ConvertStrategy::CamelCase, to: ConvertStrategy::SnakeCase)]
    public $name;
    
    [#ConvertStrategy(fromArray: ConvertStrategy::CamelCase, toArray: ConvertStrategy::SnakeCase)]
    public $age;
 
}
```

**Comment by WendellAdriel** [comment]
The package already provides a way to do this.

The "from" strategy you can do it with the mapping feature: https://wendell-adriel.gitbook.io/laravel-validated-dto/basics/mapping-dto-properties

The "to" strategy you can do it with the transformation feature: https://wendell-adriel.gitbook.io/laravel-validated-dto/basics/transforming-dto-data that already allows you to create custom transformations: https://wendell-adriel.gitbook.io/laravel-validated-dto/basics/transforming-dto-data#custom-transforming and has support for nested data: https://wendell-adriel.gitbook.io/laravel-validated-dto/basics/transforming-dto-data#transforming-nested-data

If what you're proposing is different, please show me some use cases on how it would work and what are the advantages over what the package already provides and/or create a PR with the implementation.

**Comment by meysam1717** [comment]
I'v already red the documentation and saw this mapping options.
But it's could be redundant if I should do it for all properties.

Think about it that I have a DTO with camelCase naming convention and I want parse a response from a third party that returns me snake_case and finally I want to transform it to PascalCase.

I should map all my fields one by one and it's handy.
I could not have different transformation in different methods.
Like I want to have snake_case in fromArray and kebab-case in fromJson.

I think mapData and mapToTransform should use for changing fields name and convert/transform strategies  should use for this reasopn.

**Comment by WendellAdriel** [comment]
For the DTO properties, I don't see any benefits of converting for the DTO itself, so the "from" strategy IMO won't have much impact.

Now converting to something, that makes sense, but this is already doable if you create a Custom Transforming method like the example we have in the docs here: https://wendell-adriel.gitbook.io/laravel-validated-dto/basics/transforming-dto-data#custom-transforming

```php
public function toObject(): object
{
    return (object) $this->buildDataForExport();
}
```

You could create a `toPascalCase` or `toSnakeCase` or `toCamelCase` or anything else that you need, even apply it to a Trait and add to the needed DTOs.
