### ISSUE TITLE
A question about toArray()

### ISSUE THREAD

**Issue by xingyunxlm** [WendellAdriel/laravel-validated-dto#93]
If a property does not have a default value set and is assigned a value after the class is initialized, toArray will not return the property value.
eg:
```
class TestDTO extends SimpleDTO
{
    public ?int $num;
    protected function defaults(): array
    {
        return [];
    }

    protected function casts(): array
    {
        return [];
    }
}
$testDTO = TestDTO::fromArray([]);
$testDTO->num = 1;
var_dump($testDTO->toArray()); // output []
var_dump($testDTO->num); // output 1
```

**Comment by WendellAdriel** [comment]
That's a nice catch @xingyunxlm! 🔥 
Thanks for the heads up! 💪 

I released v3.10.1 with a fix for this, you can check the PR with the fix here: #94
